name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - README.md
      - .github/**
jobs:
  test:
    name: Unit Test
    strategy:
      matrix:
        platform: [ linux, windows, macos, android, ios ]
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest
          - platform: macos
            os: macos-latest
          - platform: android
            os: ubuntu-latest
          - platform: ios
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: JVM Unit Test
        run: ./gradlew cleanJvmTest jvmTest
        if: ${{ matrix.platform == 'linux' || matrix.platform == 'windows' || matrix.platform == 'macos'}}
      - name: Android Unit Test
        run: ./gradlew cleanTestDebugUnitTest testDebugUnitTest
        if: ${{ matrix.platform == 'android' }}
      - name: iOS Unit Test
        run: ./gradlew cleanIosSimulatorArm64Test iosSimulatorArm64Test
        if: ${{ matrix.platform == 'ios' }}
      - name: Publish Test Results (ubuntu)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          files: ./**/build/test-results/**/*.xml
      - name: Publish Test Results (windows)
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          files: ./**/build/test-results/**/*.xml
      - name: Publish Test Results (macos)
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          files: ./**/build/test-results/**/*.xml
      - name: Upload HTML reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.platform }}-results-html.zip
          path: ./**/build/reports/tests
      - name: Upload XML Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-results-xml.zip
          path: ./**/build/test-results/**/*.xml

#  publish-test-results:
#    name: Publish Unit Tests Results
#    needs: test
#    runs-on: ubuntu-latest
#    if: always()
#
#    steps:
#      - name: Download Artifacts
#        uses: actions/download-artifact@v3
#        with:
#          path: artifacts
#
#      - name: Publish Unit Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        with:
#          files: artifacts/**/*results-xml.zip
